version: '3.8'
services:
  web:
    env_file:
      - ./.env
    build: .
    command: flask run --host=0.0.0.0
    environment:
      SECRET_KEY: ${SECRET_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/code
    ports:
      - "8080:5000"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_DB: "${DB_DB}"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: